name: Build Docs
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  doxygen:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Chocolatey
        uses: crazy-max/ghaction-chocolatey@v3
      - name: Install Doxygen & Graphviz
        run: |
          choco install -y doxygen.install graphviz
      - name: Build docs with Doxygen
        run: doxygen Doxyfile
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs_build/html
  deploy:
    needs: doxygen
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
